### ISSUE TITLE
core(App): getDefaultPath still calls Immutable .filter/.first on Collections plain-object slice — every collection route crashes to error boundary (DCMS-1667 regression) — DCMS-1674

### ISSUE THREAD

**Issue by sempostma** [laikacms/decap-cms#1674]
## Rung/scenario

Rung 1 (real editor on demo `test-repo` backend). Any authenticated navigation to a collection URL fires an unrecoverable React error boundary — the whole app shell is replaced by the generic "There's been an error - please open an issue on GitHub" screen. Reproduces on every collection: `posts`, `restaurants`, `faq`, `pages`, `settings/entries/general`, `settings/entries/authors`, `kitchenSink`.

## Repro

1. `git checkout 8031f4d2d` (current `origin/main` HEAD, DCMS-1667 merge)
2. `npm ci`
3. `npm run build:demo`
4. `npx http-server -c-1 dev-test -p 8080`
5. Open `http://localhost:8080/`, click **Login** (test-repo backend, alice)
6. Navigate to `#/collections/posts` (or any other collection)

Actual: full-page error screen with `TypeError: e.filter is not a function`, no navigation possible except back to `/`. Same result with a fresh empty browser profile — not a stale-localStorage issue.

## Expected vs actual

- **Expected:** Posts list (or the target collection list) renders normally.
- **Actual:** app shell unmounted; only the error boundary content is visible.

## Root cause

Introduced by 8031f4d2d (DCMS-1667, PR #1672 "core: migrate collections state slice off Immutable"). The `collections` state slice went from `Immutable.OrderedMap` to a plain object (`fromJS(collection).toObject()` in `packages/decap-cms-core/src/reducers/collections.ts`). Two consumers in `packages/decap-cms-core/src/components/App/App.js` were not migrated and still call Immutable APIs against the new plain-object shape:

```js
// packages/decap-cms-core/src/components/App/App.js:49-56
function getDefaultPath(collections) {
  const first = collections.filter(collection => collection.get('hide') !== true).first();
  if (first) {
    return `/collections/${first.get('name')}`;
  } else {
    throw new Error('Could not find a non hidden collection');
  }
}
```

Plain objects have no `.filter` → throws at `App.js:50`. `getDefaultPath` is invoked from **two** render paths in the same file (`App.js:119` and `App.js:260`), so the error fires on every route change through the App component — including any `#/collections/:name` URL. React's error boundary catches it and swaps in the "Please open an issue" screen.

Companion breakage in the same file that will surface as soon as line 50 is fixed:

```
App.js:114   Boolean(collections.get(collectionName))
App.js:125   const collectionExists = collections.get(name);
```

These also call `.get()` on a plain object; they'll return `undefined` for every name (silent) unless converted to `collections[collectionName]`. The `mediaLibrary.get(...)` calls on 394-396 are a separate slice and out of scope for this issue.

Source-map ground truth: `qO` (crash frame) → `App.js:67:28`, filter, and `GO.render` frame → `App.js:240:24`, `getDefaultPath`. (Column numbers are the built demo bundle, verified via `dev-test/dist/decap-cms.js.map`.)

## Evidence

- Repro script: `browser-sim/DCMS-0729q-nested-crash-repro.mjs` — probes 7 collection URLs, all render the error screen.
- Fresh-profile confirmation: `browser-sim/DCMS-0729q2-fresh-profile.mjs`.
- Screenshots (persistent-profile run):
  - `browser-sim/shots/2026-07-29T*-0729q-posts.png`
  - `browser-sim/shots/2026-07-29T*-0729q-pages.png`
  - `browser-sim/shots/2026-07-29T*-0729q-kitchenSink.png`
- Console (repeats per re-render):
  ```
  TypeError: e.filter is not a function
      at qO (http://localhost:8080/dist/decap-cms.js:62:60572)
      at GO.render (http://localhost:8080/dist/decap-cms.js:62:63022)
      at $s, ol, uc, sc, ac, Ku, zc, Mc (react-dom internals)
  ```
- No network `requestfailed`, no non-2xx responses — pure client-side crash.
- Last known-good demo commit for this identical repro: `61329340b` (2026-07-28, verified working in prior user-sim run).

## Acceptance criteria

- [ ] `getDefaultPath` in `App.js` handles the plain-object `Collections` shape (e.g. `Object.values(collections).find(c => c.hide !== true)`, then `c.name` for the returned collection).
- [ ] `App.js:114` and `App.js:125` `collections.get(name)` calls converted to plain-object access.
- [ ] `npm run build:demo` + `dev-test` demo: alice login → `#/collections/posts` renders 23 post cards with 0 console errors and 0 pageerrors.
- [ ] All 7 collection routes probed in `DCMS-0729q-nested-crash-repro.mjs` render without the error boundary.
- [ ] Regression guard: unit test that mounts `App` with a plain-object `collections` state slice and asserts `getDefaultPath` returns a valid route.
