### ISSUE TITLE
typecheck red on main: minimatch named-export mismatch in git-lfs-client.ts

### ISSUE THREAD

**Issue by sempostma** [laikacms/decap-cms#1795]
main branch \`pnpm typecheck\` fails:

\`\`\`
packages/decap-cms-backend-github/src/git-lfs-client.ts(1,10): error TS2724: '"minimatch"' has no exported member named 'minimatch'. Did you mean 'Minimatch'.
\`\`\`

Introduced by #1591 (DCMS-1417 git lfs support). Blocks the fleet husky pre-push gate for every PR whose diff touches shared files brought in via rebase/merge on top of main — hit while landing #1794.

Fix: import \`{ Minimatch }\` (capitalized) or use the correct export from the installed \`minimatch\` version in \`git-lfs-client.ts\`.
